name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
    contents: write    
    
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: swift-portable-${{ github.ref_name }}.zip
    steps:
      - uses: actions/checkout@v4
      
      - name: installer
        shell: cmd
        run: |
          curl "https://download.swift.org/swift-${{ github.ref_name }}-release/windows10/swift-${{ github.ref_name }}-RELEASE/swift-${{ github.ref_name }}-RELEASE-windows10.exe" -L --output installer.exe
          
      - name: innoextract 
        shell: cmd
        run: |
          installer.exe /passive /quiet &&^
          cd /d "C:\Program Files\Swift" &&^
          7z.exe a "${{ github.workspace }}\${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
